### ISSUE TITLE
linea del tiempo- Ana Kimberly Hernández Pérez 

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-7-Anakimberly#1]
[LINEA DEL TIEMPO WEB .pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-Anakimberly/files/9795726/LINEA.DEL.TIEMPO.WEB.pdf)

**Comment by ErikCuevas03** [comment]
20, el trabajo tiene creatividad

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
